add_requires("serial")
add_requires("spdlog")
add_requires("tl_expected")

target("rplidar")
    set_kind("static")
    add_files("src/*.cpp")
    add_headerfiles("include/(RPLidar.h)")
    add_includedirs("include")
    add_packages("serial", "spdlog")
    add_packages("tl_expected")
